### ISSUE TITLE
Sessao home

### ISSUE THREAD

**Issue by tomasmanueltm** [emersoncarneirodasilva/minha-galeria#2]
adicionada interação

**Comment by emersoncarneirodasilva** [comment]
Ficou muito lindo, fico muito grato por ter melhorado o projeto!!!

**Comment by tomasmanueltm** [comment]
Eu estou com um projeto para desevolver, trata-sede uma loja de vendas de
gelado. Ao busca referencias me deparei com seus projetos e me imprecionou
bastante!

Goataria de trocar algumas ideias contigo, meu Whatsapp

wa.me/+24492916942

+244929916942

Linkedin
Www.linkedin/in/tomasmanueltm

Portfolio
tomasmanueltm.github.io/portfolio
No dia 18/08/2022 15:05, "Emerson Carneiro da Silva" <
***@***.***> escreveu:
